# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX = "ubuntu/xenial64"
CPUS = "2"
HOST_NAME = "matlab"
MEMORY = "4056"
MAC_ADDRESS = "************"
PRIVATE_IP = "192.168.7.7"

Vagrant.configure("2") do |config|

  config.vm.provision "shell" do |s|
    s.path = "provision.sh"
  end

  config.vm.provider :virtualbox do |vb|
   vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]
   vb.customize ["modifyvm", :id, "--memory", MEMORY]
   vb.customize ["modifyvm", :id, "--cpus", CPUS]
   vb.customize ["modifyvm", :id, "--ioapic", "on"]
   vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.define "#{HOST_NAME}" do |c|
    c.vm.box = "#{BOX}"
    c.vm.hostname = "#{HOST_NAME}"
    c.vm.network :private_network,  ip: PRIVATE_IP, :mac => MAC_ADDRESS
  end

end
